  security:
     oauth2:
         client:
             clientId: 394224039572-89vddsfh6ctu0ipgdkjjlc5cvnarhsum.apps.googleusercontent.com
             clientSecret: WPtHcaG5zVTn5zvBuBJXvNwL
             accessTokenUri: https://www.googleapis.com/oauth2/v3/token
             userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
             tokenName: oauth_token
             authenticationScheme: query
             clientAuthenticationScheme: form
             scope: profile email
         resource:
             userInfoUri: https://www.googleapis.com/userinfo/v2/me
             preferTokenInfo: false