security:
  oauth2:
    client:
      accessTokenUri: https://oauth2.googleapis.com/token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
      tokenName: oauth_token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    resource:
      preferTokenInfo: false
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
spring:
  datasource:
    url: postgres://wplrkghdbnosrf:c931b9be2836f8ab82738fb8edad0b06e91f459fe0966d8565c8fbc6f41cb300@ec2-52-2-43-242.compute-1.amazonaws.com:5432/db2ac87c07pcem
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          clientSecret: 7aRCcC7awsyswNsASo_VTA8f
          google:
            client-id: 394224039572-89vddsfh6ctu0ipgdkjjlc5cvnarhsum.apps.googleusercontent.com
